# Generated by Django 3.1.4 on 2020-12-10 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201210_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='discription',
            new_name='description',
        ),
    ]
