# Generated by Django 3.1.4 on 2020-12-10 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201210_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='titel',
            new_name='title',
        ),
    ]
